### ISSUE TITLE
#4

### ISSUE THREAD

**Issue by paulomcnally** [celopez1990/IdentificadorLlamadasNi#4]

**Comment by celopez1990** [comment]
puntofácil bloqueo su login regular, su formulario de recuperación de passwords y su formulario de registro, creo que lo único que funciona ahora mismo es el login con facebook... y bloquean la cuenta cada vez que accedo por ese método para coger una cookie válida... sigo buscando métodos...

**Comment by paulomcnally** [comment]
También esta habilitada la creación de cuentas con gmail.

Tengo algunas de unos cuantos usuarios. Siguen bloqueando la cookie.

Sería tener acceso a su base de datos de usuarios para obligarlos a bloquear cada cuenta de cada usuario o usar cuentas de fb.

Lo ideal sería crear un script que cree una cuenta, obtenga la cookie y la almacene en una base de datos, para así automatizar esto. Podría ser con [selenium](http://www.seleniumhq.org/).

Voy a trabajar el script.
